lib/foundation_web/router.ex
defmodule FoundationWeb.Router do
  use FoundationWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug FoundationWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :auth do
    plug FoundationWeb.Plugs.RequireAuth
  end

  scope "/auth", FoundationWeb do
    pipe_through :browser

    get "/signout", AuthController, :delete
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :new
  end

  scope "/", FoundationWeb do
    pipe_through [:browser, :auth]

    resources "/videos", VideoController, only: [:new, :create]
  end

  scope "/", FoundationWeb do
    pipe_through :browser # Use the default browser stack

    resources "/videos", VideoController, only: [:index, :show, :delete]
    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", FoundationWeb do
  #   pipe_through :api
  # end
end

lib/foundation_web/views/layout_view.ex
defmodule FoundationWeb.LayoutView do
  use FoundationWeb, :view
end

lib/foundation_web/templates/layout/_navigation.html.eex
<div class="title-bar" data-responsive-toggle="my-menu" data-hide-for="medium">
  <button class="menu-icon"></button>
  <div class="title-bar-title">Menu</div>
</div>
<div class="top-bar" id="my-menu">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text">Foundation</li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="menu">
      <%= if @conn.assigns[:user] do %>
        <li class="menu-text">Welcome, <%= @conn.assigns.user.first_name %></li>
        <li><%= link "Videos", to: video_path(@conn, :index) %></li>
        <li><%= link "Add video", to: video_path(@conn, :new) %></li>
        <li><%= link "Sign out", to: auth_path(@conn, :delete), class: "button alert" %></li>
      <% else %>
        <li><%= link "Videos", to: video_path(@conn, :index) %></li>
        <li><%= link "Sign in with Google", to: auth_path(@conn, :request, "google", scope: "email profile", class: "button") %></li>
      <% end %>
    </ul>
  </div>
</div>

lib/foundation_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Phoenix learning app">
    <meta name="author" content="Ladrone Vincet">
    <meta name="contribution-to" content="Brian Empory">
    <meta name="whose-blog-is" content="https://medium.brianemory.com/@thebrianemory">
    <meta name="this-is-not" content="How one shoud use meta tags">

    <title>Hello Foundation!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <%= render "_navigation.html", conn: @conn %>
      <p class="callout primary flash-alert" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="callout alert flash-alert" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>$(document).foundation()</script>
  </body>
</html>